### PR TITLE
 	frontpage processing for person tags to be accepted & setting default to sync

### PR DESCRIPTION
**Pull request by acegiak**

### CODE REVIEW

**Comment by pfefferle** [comment]
this merge request is very confusing ;)

is the only change, the `sync` flag?

**Comment by dshanske** [comment]
I think that @acegiak wants the Page ID for the homepage to be settable by user option, not just filter. I think that is doable.

**Comment by acegiak** [comment]
Nono I ended up using the hook to do that in a different thread.

The only two things this PR are for are setting  the default to sync rather than async and allowing the webmention endpoint to be displayed on the front page so that you can receive person tags

**Comment by dshanske** [comment]
@acegiak I see.. not showing it is creating an issue for exotic Webmentions.

**Comment by dshanske** [comment]
I think I have another way to approach this.

**Comment by dshanske** [comment]
Let me give it a go

**Comment by pfefferle** [comment]
Is there perhaps a generic way? like an action or a hook? I don't want to add features that are not used by the core, but by a plugin instead.

**Comment by dshanske** [comment]
That is what I am thinking. Make the is_singular and pings_open check a function, and filter it. So anyone can open it for any given URL.

**Pull request closed without merging**
