### PR TITLE
Introduce Webmention Comments Template

### PR DESCRIPTION
**Pull request by dshanske**
This introduces a simple webmentions comment template. It actually does it differently than the Semantic Linkbacks template. Instead of using the comment form hooks, it actually loads the template, if the setting is enabled, then that template loads the theme template. So the original comment template, which is filtered to only show non-webmention comments, shows as intended by the theme author. And the new template just loads before it.

This is a very barebones implementation, and I expect we'll iterate on it with more features.

### CODE REVIEW

**Comment by dshanske** [comment]
@pfefferle Can you have a look?

**Comment by pfefferle** [comment]
Will do! I had vacations until yesterday ;)

**Comment by dshanske** [comment]
Didn't realize..  hope you had fun

**Comment by dshanske** [comment]
> Will do! I had vacations until yesterday ;)

@pfefferle Just waiting on this...not trying to be a bother.

**Comment by pfefferle** [comment]
I get an error when I visit the post permalink site:

```PHP
Warning: require_once(/var/www/html/wp-content/themes/twentytwentytwo/comments.php): failed to open stream: No such file or directory in /var/www/html/wp-includes/template.php on line 770 Fatal error: require_once(): Failed opening required '/var/www/html/wp-content/themes/twentytwentytwo/comments.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-includes/template.php on line 770 
```

**Comment by dshanske** [comment]
How does it look overall? I see you fixed a locate issue

**Comment by dshanske** [comment]
@pfefferle Any chance on this one?

**Comment by pfefferle** [comment]
I am working on some dummy/test data, otherwise it is hard to see the result.

**Review by pfefferle — APPROVED** [review]
LGTM

**Pull request merged**
