### PR TITLE
Make admin stuff start from a hook

### PR DESCRIPTION
**Pull request by szepeviktor**
pluggable :)

### CODE REVIEW

**Comment by pfefferle** [comment]
I see! 

I like the example you referenced, can you help restructuring the plugin a bit?

**Comment by szepeviktor** [comment]
Setting go from constants to Hooks

```
// defined( 'WEBMENTION_ALWAYS_SHOW_HEADERS' ) || define( 'WEBMENTION_ALWAYS_SHOW_HEADERS', 0 );

// In should_show_headers()
if ( apply_filters( 'webmention_always_how_headers', false ) )
```

Class loading will be done by Composer autoload

```
// require_once dirname( __FILE__ ) . '/includes/class-webmention-admin.php';

// NOTHING :)
```

Hooked functions go into a class

```
// function webmention_comment_form() {
```

Do you agree?

**Comment by dshanske** [comment]
I personally am reluctant to use composer autoload because it creates a large plugin dependency. I usually limit composer to a development dependency myself.

**Comment by szepeviktor** [comment]
> it creates a large plugin dependency.

Yes, currently with `composer/installers` it is +500 KB
But distributing only the autoload:

```
$ du -sh vendor/
56K     vendor/
```

:)

**Comment by szepeviktor** [comment]
@pfefferle Sad End?

**Comment by pfefferle** [comment]
I messed up with the branching... and github seems to close some merge requests because of this :(

**Comment by pfefferle** [comment]
I will work throught the MRs to try to fix them... I even can't reopen them! argh!

**Comment by szepeviktor** [comment]
Thank you.

**Pull request closed without merging**
