### PR TITLE
Parentheses

### PR DESCRIPTION
**Pull request by dshanske**
Made an error with a parentheses I missed. Need to push this because it is messing things up.

### CODE REVIEW

**Comment by pfefferle** [comment]
can you please update your npm and run grunt again? you are reverting my changes for the pot and readme files.

**Comment by dshanske** [comment]
@pfefferle Did this work?

**Comment by pfefferle** [comment]
Yes, thanks

**Comment by dshanske** [comment]
@pfefferle Sorry about the parentheses. I am going to have to think of a test as I make the next improvements

**Pull request merged**
