### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by dshanske**
- Save Fragments of URLs
- Add Avatar Support to Webmentions
- Fix issue with dupes due incorrect query argument

### CODE REVIEW

**Comment by pfefferle** [comment]
thanks a lot! I have only one point, I think we should use a more descriptive name for the fragment, like `webfinger_target_url_fragment` or `webfinger_url_fragment`... what do you think?

**Comment by dshanske** [comment]
It isn't webfinger, it is webmention. But the longer name is fine.

**Comment by dshanske** [comment]
I would say webmention_target_url and webmention_target_fragment

**Comment by pfefferle** [comment]
I always mix these two names up... I like your suggestion!

**Comment by pfefferle** [comment]
Can you add the changes or should I update the code after the merge?

**Comment by dshanske** [comment]
Done.

**Comment by pfefferle** [comment]
Sorry, but I think you broke something...

**Comment by dshanske** [comment]
I will check. I did the code last night. I was exhausted. I thought I checked it this morning when I was awake, but must have missed something. Will double check.

**Comment by dshanske** [comment]
I keep breaking my never commit while tired policy

**Comment by pfefferle** [comment]
I found it... the slash in line 52 ;)

**Comment by dshanske** [comment]
I don't see a slash in line 51 of the receiver? What do you see? I just tested it and it worked.

**Comment by pfefferle** [comment]
sorry, my mobile app seems to show different line numbers. I commented inline.

**Comment by dshanske** [comment]
I think I found the stray slash.

**Comment by pfefferle** [comment]
sorry for beeing so pedantic, but can you also fix the codeclimate issues? https://codeclimate.com/github/pfefferle/wordpress-webmention/pull/127

Travis has problems with phpunit and php 5.6, so we don't have to care atm.

**Comment by pfefferle** [comment]
Travis seems to be fixed now...

**Comment by dshanske** [comment]
Fixed now, I think

**Comment by pfefferle** [comment]
https://github.com/pfefferle/wordpress-webmention/pull/127/files#diff-4a405db849c60f60b9e32bde3bfe0096R62

**Comment by dshanske** [comment]
I'm not sure what you are trying to convey.

**Comment by pfefferle** [comment]
the indents are still wrong for that line and the following

**Pull request merged**
