### PR TITLE
Webmention Aware Notifications

### PR DESCRIPTION
**Pull request by dshanske**
This adds the webmention type as a supported notifications type. All the text is the same as in default WordPress. Much cleaner than before.

### CODE REVIEW

**Comment by dshanske** [comment]
Any news on this Pull?

**Comment by pfefferle** [comment]
I was at vacation, sorry... Will have a look at it on monday...

**Comment by dshanske** [comment]
Didn't realize you were on vacation.

**Comment by pfefferle** [comment]
I have checked this and really can't find any advantages against the core implementation. Can you explain me the advantages?

**Comment by dshanske** [comment]
The core implementation treats webmentions like comments instead of like pingbacks. This has them treated like pingbacks.

**Comment by dshanske** [comment]
I'm closing this pull request in the hopes of resolving my Ticket with WordPress to make this less invasive to write. 

In the interim, I think I may, as inelegant as it is, create a plugin with a pluggable version of the notification functions that does know about webmentions.

**Pull request closed without merging**
