### PR TITLE
some improvements and removed unused code

### PR DESCRIPTION
**Pull request by pfefferle**

### CODE REVIEW

**Comment by dshanske** [comment]
We're not going to sanitize it using our function?

**Comment by pfefferle** [comment]
The code I removed is never be used! Besides of that, we have to check sanitisation! Best practice is sanitize as late as possible, so we should add it at to_array and to_commentarray (some of the attribs are not Esche/sanitized at all!)

**Comment by pfefferle** [comment]
Or we have to update the setters adders to also sanitize

**Comment by dshanske** [comment]
Good point about moving it.

**Review by dshanske — APPROVED** [review]

**Pull request merged**
