### PR TITLE
replaced link matching regex with http://daringfireball.net/2010/07/i…

### PR DESCRIPTION
**Pull request by petermolnar**
added regex from http://daringfireball.net/2010/07/improved_regex_for_matching_urls to match all urls ( in-text & markdown ); tested, working

since it's kind of specific and may not fit everyone's needs I just wanted to add as a possibility.

### CODE REVIEW

**Comment by pfefferle** [comment]
First of all: Thanks for the pull request :)

...but I have tried the code with a demo MD text and it seems to break when using something like:

```Markdown
[https://github.com](https://github.com)
```

**Comment by pfefferle** [comment]
What do you think about adding something like:

```PHP
preg_match_all("/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/i", $post->post_content, $matches )
```

as a second check?

**Comment by petermolnar** [comment]
That is weird, it is working for me, though I'm under PHP 5.6.8 if that matters.

The foreach is there explicitly to sort the [https://github.com](https://github.com) trouble because in those cases the match goes into $matches[2] and not into [1] so I need to override that.
I'd fix the regex, but this is black magic level and way beyond me.

**Comment by petermolnar** [comment]
I'll look into this deeper.

**Comment by pfefferle** [comment]
Can you post a link to a gist with your demo text here? So that we could test it with the same data?

**Comment by pfefferle** [comment]
I used 5.5.20 btw.

**Comment by petermolnar** [comment]
I've made a few tests and the daingfireball regex seems to be overreacting in the (url)[url] case with a few hundred thousand backtracks.
So I'm currently checking 
```
if (preg_match_all("/\b(?:http|https)\:\/\/?[a-zA-Z0-9\.\/\?\:@\-_=#]+\.[a-zA-Z0-9\.\/\?\:@\-_=#]*/i", $post->post_content, $matches)) {
        $links = $matches[0];
    }
```
which I put together from at least 3 different patterns.

The text I'm using now:
```
[https://domain.com/test](https://domain.com/test)

[Link to test 1](https://domain.com/test-1)

https://domain.com/test-2

<a href="https://domain.com/test-3">https://domain.com/test-3</a>

<a href="https://domain.com/test-3">Link to test-3</a>
```

so far it matches every url, so an array_unique is still needed.

**Comment by pfefferle** [comment]
The question is, can we ping every URL or do we have to skip things like:

```
https://domain.com/test-2
```

because they might be text-only and not (hyper)linked to the URL.

**Comment by petermolnar** [comment]
That's the thing; since I'm writing my WP posts in Markdown ( and I store them in md as well ), I'm expecting any urls to be picked up, since they are all converted to links.

Also, there is the make_clickable function in WP which I don't know if it's by default applied, but if yes, then everyone is expecting all urls to become links, thus pingbacks, in my opinion.

**Comment by pfefferle** [comment]
Good point, will check the `make_clickable` thing later.

**Comment by pfefferle** [comment]
This is also problematic, because it does not support Umlauts in the domain name or the path.

**Comment by pfefferle** [comment]
Why have you closed it? I think this is still a good idea!

**Comment by petermolnar** [comment]
Because it messes up things too much; I've ended up using your already in place filter to re-parse my posts which solved all my issues.

**Pull request closed without merging**
