### PR TITLE
Replace with built-in WordPress functions

### PR DESCRIPTION
**Pull request by dshanske**
This replaces make_absolute_url with the built in version of same, and replaces a pure instance of parse_url, with wp_parse_url...a wrapper which supports schemeless URLs on earlier versions of PHP

### CODE REVIEW

**Comment by pfefferle** [comment]
isn't it `make_absolute_url` instead?

**Comment by dshanske** [comment]
Correct, it is late, and I am stuck in the airport waiting to get home. I shouldn't have tried to write code this late.

**Comment by pfefferle** [comment]
No problem, I am sorry that I forgot to merge and that you are that patient and persistent!

**Comment by pfefferle** [comment]
The `WP_Http` is a very nice change BTW (didn't know about the `make_absolute_url` before). The less code the better ;)

**Comment by dshanske** [comment]
I hope to make a lot of positive improvements in the codebase. If you skimmed the experimental version, I'm playing with a lot of different ideas and testing them before I write the pull requests. The ones I plan on sending first are things like this that remove code.

**Comment by pfefferle** [comment]
If you update the pull request, I will merge it.

**Comment by dshanske** [comment]
Updated

**Comment by pfefferle** [comment]
thanks :)

**Pull request merged**
