### PR TITLE
Refactor Based on Ideas from the Draft Specification

### PR DESCRIPTION
**Pull request by dshanske**
Addresses Issue #66, #65, #64.

Also sets the stage for additional adjustments.

### CODE REVIEW

**Comment by pfefferle** [comment]
Thanks a lot! I will have a look at your changes this evening!

...and by the way: indents :laughing:

**Comment by dshanske** [comment]
Still challenged in that area.

**Comment by dshanske** [comment]
Indent fix, and change in hooks.

**Comment by dshanske** [comment]
Now Addresses #52 in part by adding support to react to a status code other than 200. Addresses in part #68 in a similar way by allowing for per-media source verification and adjusting the timeout and limit to be more consistent.

**Comment by dshanske** [comment]
@pfefferle Sorry for continuing to add to this PR, but I don't want to stop my momentum here.

**Comment by pfefferle** [comment]
The search/replace messed up the code a lot. Please try the next search replace with case sensitive matching! There are still wrong function names and actions.

Sorry for beeing so inactive these days but we moved and I still have no internet in my new home. Hopefully this friday, so I can have a deeper look at your changes and merge them.

**Comment by dshanske** [comment]
There have been several articles in the WordPress community of late. I think it is a good time to see what can be done to enhance the plugin.

**Comment by dshanske** [comment]
@petermolnar added some features to his webmentions plugin that I think would work here. Going to try to bring some of them over. Such as having certain code broken into functions.

**Comment by dshanske** [comment]
I keep committing on this. I hope all of the changes are an improvement.

**Comment by pfefferle** [comment]
I have internet since monday, so I hope I can have a look at your changes this weekend!

thanks so far!

**Comment by dshanske** [comment]
I hope you say that after you review them. Congratulations on your internet, I know that was a long battle. After these changes, I want to make an attempt at an asynchronous handler.

**Comment by pfefferle** [comment]
;)

I had some quick looks and I like most of your changes and your re-structuring... but I would re-organize some small parts and fix some indents ;)

**Comment by dshanske** [comment]
I ran the whole thing through phpcbf. I thought that was supposed to help me with my indenting handicap. 

With the reorganization, I keep making additional reorganizations as I have ideas to make it better.

**Comment by dshanske** [comment]
I'm going to try to leave it alone till you have a chance to look at it.

**Comment by dshanske** [comment]
I'm going to rescope this, work on it elsewhere, and slip my commits in in more manageable pieces.

**Pull request closed without merging**
