### PR TITLE
Undefined var in is_source_whitelisted()

### PR DESCRIPTION
**Pull request by szepeviktor**
Discovered by @phpstan

### CODE REVIEW

**Comment by szepeviktor** [comment]
@pfefferle Please consider running PHPStan
https://packagist.org/packages/szepeviktor/phpstan-wordpress

**Comment by szepeviktor** [comment]
`"php": ">=5.6.0"` opens a way to class autoloading! :)

**Comment by dshanske** [comment]
Thank you. I had fixed that in a PR that was abandoned. Had forgotten to submit it separately.

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
