### PR TITLE
Update tests and make `u-url` attrib optional for post-type discovery

### PR DESCRIPTION
**Pull request by pfefferle**

### CODE REVIEW

**Comment by pfefferle** [comment]
please review @snarfed and @dshanske

**Review by dshanske — APPROVED** [review]
Not necessarily a fan of this, but I see the necessity.

**Comment by pfefferle** [comment]
Can you explain a bit more?

**Comment by dshanske** [comment]
> Can you explain a bit more?

I just get nervous about regex matching sometimes. I'm wondering if DOMDocument might be more consistent with what we did elsewhere. But it isnt' an issue.

**Comment by pfefferle** [comment]
Merge this and think about a better way to get links in the content later?

**Comment by dshanske** [comment]
I think so

**Pull request merged**
