### PR TITLE
Fix Issue 93

### PR DESCRIPTION
**Pull request by dshanske**
Related #93

### CODE REVIEW

**Comment by pfefferle** [comment]
this change has indention and syntax errors

**Comment by dshanske** [comment]
I ran in through phpcbf. I thought it was supposed to catch that.

**Comment by pfefferle** [comment]
this should be indented https://github.com/pfefferle/wordpress-webmention/pull/94/files#diff-5ac85cf40a7cd031c3978d311c357cdaR171

and there is a failing comma at the end https://github.com/pfefferle/wordpress-webmention/pull/94/files#diff-5ac85cf40a7cd031c3978d311c357cdaR175

**Comment by dshanske** [comment]
I see the comma at the end, I didn't add that. Guess I need to hand check the output when I use auto correct.

**Comment by dshanske** [comment]
That's it, I am taking @snarfed 's advice and trying to write unit tests.

**Comment by pfefferle** [comment]
;)

this would be awesome!

**Comment by dshanske** [comment]
I did some a while back based on endpoint discovery from webmentions.rock . I am going to try to write more in my 'playground'. I'd rather break things, perfect them, then try to move them to stable.

**Pull request closed without merging**
