### PR TITLE
Set created at time only for new comments.

### LINKED ISSUE #360: Webmention Created At
The webmention created at is overwritten on update.

### PR DESCRIPTION
**Pull request by dshanske**
Resolves #360 as this will only set this property if it is a new comment.

### CODE REVIEW

**Comment by pfefferle** [comment]
And what about updated_at?

**Comment by dshanske** [comment]
We don't have an updated at.

**Comment by pfefferle** [comment]
oh, this is only for posts.

**Comment by pfefferle** [comment]
Do we use `webmention_created_at` anywhere?

**Comment by dshanske** [comment]
Comment date is set based on published date of the Webmention.. Creation could therefore be different

**Comment by pfefferle** [comment]
Isn't it technically not possible to set the `comment_date` to the date that comes with the Webmention ping, or do you think this should be the local `created_at`?

**Comment by pfefferle** [comment]
I am not sure I got this!?!

**Comment by dshanske** [comment]
So, the  comment date is set using the published date. The created date is meant to reflect when the comment was created. The difference being that they are not always the same time.

**Comment by dshanske** [comment]
Still confused about this. This is the actual time the webmention was created. The comment date field is the published date of the post the webmention came from.

**Comment by pfefferle** [comment]
But the difference should be minutes... do we use the meta date for something?

**Comment by dshanske** [comment]
Maybe we are better off with modified and stop storing created.

**Comment by pfefferle** [comment]
I am just curious!

**Comment by dshanske** [comment]
We originally put it in with an idea of tracking updates.. but we don't store updated dates.

**Comment by pfefferle** [comment]
That would make more sense to me! That we use the comment_date for created_at and have a meta for updated_at!

**Comment by dshanske** [comment]
@pfefferle Switched to last_modified.

**Review by pfefferle — APPROVED** [review]
LGTM

**Pull request merged**
