### PR TITLE
Update Dependencies, Actions and WP Requestor

### PR DESCRIPTION
**Pull request by dshanske**
I updated the dependencies on this, and ran the tests, but noticed an issue with the wp rest api call...I found a way to reduce a function call by asking for the authorship data to be embedded. This will change the creation of future tests.

### CODE REVIEW

**Review by pfefferle — COMMENTED** [review]
I am not sure I understand the embed thing

**Comment by dshanske** [comment]
> I am not sure I understand the embed thing

https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/ - It just saves you from having to poll for the author, it adds the author object to the return. I didn't notice it before.

**Comment by pfefferle** [comment]
Awesome!

**Review by pfefferle — APPROVED** [review]
LGTM!

**Pull request merged**
