### PR TITLE
Add mf2 library

### PR DESCRIPTION
**Pull request by pfefferle**
@dshanske what do you think?

### CODE REVIEW

**Comment by pfefferle** [comment]
It prefixes the Mf2 lib, so we do not have to worry about naming collisions and/or different versions. We could also easily add the emoji lib by aaronpk.

**Comment by pfefferle** [comment]
Oh god... this requires a whole lot of refactoring... will re-check later today...

**Comment by dshanske** [comment]
A bit more complicated than what I did. Will wait for you to finish the refactoring

**Comment by dshanske** [comment]
I'm not against going up to PHP5.6. I had just waited until we did something that needed it. But considering core won't allow below 5.6 anymore, isn't worth maintaining the compatibility issue in support of continuing to move forward.

**Comment by pfefferle** [comment]
@dshanske should work now. The result is nearly the same as in your mr, but it adds `Webmention` as the main namespace, so that we do not run into naming and version issues.

**Comment by dshanske** [comment]
@pfefferle But the mf2 isn't called yet. Do we want to merge it then add it actually being called?

**Comment by pfefferle** [comment]
Yes, let’s work on the autoload next and after that on the parsing thingy

**Comment by dshanske** [comment]
Then this PR is approved. I will set up a separate PR for adding the mf2 json to the comment data, then a separate one for the fetch refactoring I already wrote, then we'll start building actual usage of the mf2 data

**Comment by dshanske** [comment]
For parsing, will start simple, by the way, with h-card parsing for author name and image, and move to comment types later

**Comment by pfefferle** [comment]
Can we discuss the comment data thing? Is it a good idea to have it as part of the comment?

**Comment by pfefferle** [comment]
I would also prefer to avoid the jf2 stuff, because it felt very hacky working on that in the mf2-feed plugin.

**Comment by dshanske** [comment]
@pfefferle That is just passing it along to other functions, it never hits the database. As for jf2, only if that comment type is returned.

**Pull request merged**
