### PR TITLE
Improve Settings UI

### PR DESCRIPTION
**Pull request by moritzbappert**
Work done to revamp the plugin settings screens during #CFHack2022.

### CODE REVIEW

**Comment by jaz-on** [comment]
I'm really looking forward to seeing the first implementation of the new interface and being able to iterate!
@moritzbappert / @pfefferle if you need anything from me, let me know! The whole design is on Carolina's Figma file and I can change things on it.
I think that the content wasn't polished, I wanted to talk to you Matthias about it. My position was to make content less technical and more easy to understand on the setting page and then, Moritz implemented a tab called "more info" or something like that. That tab could provide a FAQ, give access to a tutorial for brid.gy, link to the official webmention and indieweb sites etc...

**Comment by jaz-on** [comment]
Hey @pfefferle & @dshanske what do you guy's think about this PR?
What are the things you need to solve on your side before trying to test this interface redesign?

**Comment by jaz-on** [comment]
Hi @pfefferle I'm reviving this CloudFest Hackathon 2022 PR.
Is the idea of reworking the plugin interface still something you might consider?
Or is it to be statued as a no-go?

Btw if I recall correctly, you said something about a friend of yours who could help design a new logo, right?

Please let me know if I can help with anything not too tech-oriented to help you out with the plugin! :)

**Comment by pfefferle** [comment]
sure, I still want to improve the settings/onboarding flow! I am not sure if it is exactly what we did on the Hackathon, but there are some nice ideas in it.

> Btw if I recall correctly, you said something about a friend of yours who could help design a new logo, right?

Yes, should ping him again, thanks for the reminder ;)

> Btw if I recall correctly, you said something about a friend of yours who could help design a new logo, right?

Nothing specific, but if you have feedback to the UI/UX/Readme/Texts/... feel free to file as much issues as you can :)

Nice to see that you are still around... long time no see :(

**Pull request closed without merging**
